<a href="https://colab.research.google.com/github/yangrainie/TAICA_Generative-AI/blob/main/RAG_01_%E6%89%93%E9%80%A0%E5%90%91%E9%87%8F%E8%B3%87%E6%96%99%E5%BA%AB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RAG 1｜用 EmbeddingGemma 2 與 FAISS 建立中文 RAG 知識庫

步驟:<br>
1.上傳自己蒐集到的資料(.md檔)<br>
2.擷取RAG文字與metadata(取得文件正文、標題、來源網址、整理日期等資訊。)<br>
3.chunking(文件切割):將較長的文件切成多個小區塊，並保留必要的重疊內容。<br>
4.embedding(向量嵌入):使用 EmbeddingGemma 2 將每個 Chunk 轉換成數值向量。<br>
5.建立 FAISS 向量索引:將向量加入 FAISS 索引，建立後續搜尋所需的結構。<br>
6.保存與打包知識庫:保存 FAISS 索引、Chunk 文字、ID 對照及設定檔，最後壓縮成 ZIP 匯出。

準備教材：`rag-data.zip`。

## 1. 安裝套件

使用 Sentence Transformers 載入模型、NumPy 處理向量，以及 FAISS 搜尋向量。

安裝embedding、向量資料庫需要的套件

In [ ]:
%pip install -q "sentence-transformers==6.1.0" "transformers==5.20.1" "faiss-cpu==1.15.1"

## 2. 檢查環境與集中設定

In [ ]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo
import importlib.metadata as package_metadata
import hashlib
import json
import re
import tempfile
import zipfile

import torch
import faiss
from IPython.display import display
from sentence_transformers import SentenceTransformer
from huggingface_hub import HfApi

#### **設定embedding模型、批次處理大小、運算裝置，以及套件版本資訊。**

In [ ]:
MODEL_ID = "google/embeddinggemma-2" #指定要使用的 Embedding 模型
BATCH_SIZE = 4 #每批處理幾筆資料(調小可以降低記憶體使用量)
EXPECTED_DOCUMENT_COUNT = None  # 換自己的資料的大小(預期的文件數量，實際用途要看後續程式碼)
EXPORT_ZIP_NAME = "vector_db.zip" # 匯出檔案的名稱(可以自己改名稱)

# text 本身已含標題；這裡不再從 metadata 添加標題。
DOCUMENT_TEMPLATE = "title: none | text: {text}"
QUERY_TEMPLATE = "task: search result | query: {question}"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE = (
    torch.bfloat16
    if DEVICE == "cuda" and torch.cuda.is_bf16_supported()
    else torch.float32
)
PACKAGE_NAMES = ["torch", "numpy", "sentence-transformers", "transformers", "faiss-cpu", "huggingface-hub"]
PACKAGE_VERSIONS = {name: package_metadata.version(name) for name in PACKAGE_NAMES}
print("裝置：", DEVICE, "／模型精度：", DTYPE)
if DEVICE == "cuda":
    print("GPU：", torch.cuda.get_device_name(0))
display(pd.DataFrame(PACKAGE_VERSIONS.items(), columns=["套件", "版本"]))

裝置： cuda ／模型精度： torch.bfloat16
GPU： Tesla T4

                      套件            版本
0                  torch  2.11.0+cu130
1                  numpy         2.1.3
2  sentence-transformers         6.1.0
3           transformers        5.20.1
4              faiss-cpu        1.15.1
5        huggingface-hub        1.33.0

## 3. 上傳教材 ZIP

執行後選擇第一版教材 ZIP。程式只解開 TXT；README、CSV、問題集不會匯入知識庫。中文檔名由 Python 的 ZIP 工具讀取。

In [ ]:
from google.colab import files
from pathlib import Path
import tempfile

# 1.開啟上傳視窗，選擇檔案
uploaded = files.upload()

# 2.找出上傳檔案中副檔名為.md的檔案
md_names = [name for name in uploaded if name.lower().endswith(".md")]

# 3.確認有成功上傳文件
if not md_names:
    raise ValueError("找不到.md檔案，請確認上傳的文件。")

#archive_name = zip_names[0]
#archive_bytes = uploaded[archive_name]
#SOURCE_ARCHIVE_SHA256 = hashlib.sha256(archive_bytes).hexdigest()

# 4.建立暫存資料夾
DATA_DIR = Path(tempfile.mkdtemp(prefix="rag_documents_"))

# 5.將文件寫入暫存資料夾
for name in md_names:
    target = DATA_DIR / Path(name).name
    target.write_bytes(uploaded[name])

# 6. 建立 Markdown 文件路徑清單
md_paths = sorted(
    [p for p in DATA_DIR.rglob("*")
     if p.is_file() and p.suffix.lower() == ".md"],
    key=lambda p: p.relative_to(DATA_DIR).as_posix(),
)

# 7. 顯示上傳結果
print("Markdown 文件數量：", len(md_paths))

for path in md_paths:
    print("•", path.relative_to(DATA_DIR).as_posix())

Saving AppleWatchSE3.md to AppleWatchSE3.md
Saving COROSPACE4.md to COROSPACE4.md
Saving garmin_forerunner70.md to garmin_forerunner70.md
Saving garmin_venu3.md to garmin_venu3.md
Saving PolarPacer.md to PolarPacer.md
Markdown 文件數量： 5
• AppleWatchSE3.md
• COROSPACE4.md
• PolarPacer.md
• garmin_forerunner70.md
• garmin_venu3.md

## 4. 先看一篇原始文件

請觀察「標題」「來源網址」「教材整理日期」「【內容】」「【檢索練習問題】」等欄位。不是每個欄位都適合送進 embedding。

本教材只取標題與正文。若把文件裡的練習問題也送進去，搜尋可能直接命中題目，無法公平觀察正文的檢索效果。

可修改 `SAMPLE_INDEX`，換看其他文章。

In [ ]:
#指定要查看第幾份文件。Python 從 0 開始計算，所以 0 代表第一份。
SAMPLE_INDEX = 0

#從文件路徑清單中取出第一份文件的路徑。
sample_path = md_paths[SAMPLE_INDEX]
try:
    sample_raw = sample_path.read_text(encoding="utf-8-sig") #使用 UTF-8 編碼讀取文件內容
except UnicodeDecodeError as exc:
    raise ValueError(f"{sample_path.name} 不是可讀取的 UTF-8 文字。") from exc
print("檔名：", sample_path.name)
print("=" * 50)
print(sample_raw)

檔名： AppleWatchSE3.md
==================================================
# Apple Watch SE 3

## 1. 基本資訊

- 品牌：Apple
- 型號：Apple Watch SE 3
- 推出年份：2025 年
- 產品類型：GPS 智慧手錶
- 官方售價：新台幣 7,900 元起（依錶殼尺寸與連線版本而異，購買前請確認官網價格）
- 錶殼材質：鋁金屬
- 錶殼顏色：午夜色、星光色
- 作業系統：watchOS
- 資料查詢日期：2026-10-28

## 2. 硬體規格

### 2.1 尺寸與重量

**40 公釐版本**
- 錶殼高度：40 公釐
- 錶殼寬度：34 公釐
- 錶殼厚度：10.7 公釐
- 螢幕解析度：324 × 394 像素
- 顯示面積：759 平方公釐
- GPS 版本重量：26.3 公克
- GPS + 行動網路版本重量：26.4 公克
- 適用手腕圍：130–200 公釐

**44 公釐版本**
- 錶殼高度：44 公釐
- 錶殼寬度：38 公釐
- 錶殼厚度：10.7 公釐
- 螢幕解析度：368 × 448 像素
- 顯示面積：977 平方公釐
- GPS 版本重量：32.9 公克
- GPS + 行動網路版本重量：33.0 公克
- 適用手腕圍：140–245 公釐

### 2.2 顯示器

- 顯示器類型：隨顯 Retina 顯示器，採用 OLED 與 LTPO 技術
- 峰值亮度：最高 1,000 尼特
- 最低亮度：2 尼特
- 像素密度：326 ppi
- 螢幕玻璃：Ion-X 玻璃錶面
- 耐用性：官方表示玻璃具備 4 倍抗裂能力

### 2.3 處理器與儲存空間

- 晶片：Apple S10
- 處理器：64 位元雙核心處理器
- 神經網路引擎：4 核心
- 儲存容量：64GB

### 2.4 感測器

- 第 2 代光學心率感測器
- 體溫感測器
- 指南針
- 常啟高度計
- 高 g 值加速度計
- 高動態範圍陀螺儀
- 環境光度感測器

## 3. GPS 與定位功能

- GPS：有
- 定位系統：L1 GPS、GLONASS、Galileo、QZSS、北斗
- 指南針：有
- 高度計：有，採常啟式高度計
- 健行定位：可使用指南針、座標、海拔高度、航點與 GPS 回溯等功能
- 路線功能：支援部分離線地圖及自訂路線功能，實際可用範圍依功能與地區而異

## 4. 運動與訓練功能

### 4.1 跑步功能

- 跑步活動記錄：有
- 自訂訓練：有
- 自訂體能訓練顯示畫面：有
- 訓練負荷：有
- 心率區間：有，可自訂
- 體能訓練後心率：有
- 最大攝氧量（VO₂ max）：有
- 路線競速：有
- 配速員：有
- 自動田徑場偵測：有
- 多運動訓練：有
- 跑步指標：支援步頻、步幅長度、觸地時間、垂直振幅與跑步功率
- 訓練提示：支援心率區間、配速及目標提示

### 4.2 健行功能

- 指南針與方位資訊：有
- 海拔高度及座標：有
- 自訂航點：有
- GPS 回溯：有
- 離線地圖及自訂路線：支援部分相關功能，實際可用性依地區與設定而異

### 4.3 自行車功能

- 記錄平均速度、爬升高度與距離
- 支援透過藍牙連接自行車配件
- 支援功能性閾值功率、功率區間及踏頻
- 可在 iPhone 上顯示即時動態

### 4.4 游泳功能

- 泳池游泳：有
- 開放水域游泳：有
- 自訂泳池游泳訓練：有
- 分段與自動組合：有
- 自動泳式偵測：有
- 浮板偵測：有
- 游泳效率指標（SWOLF）：有
- 記錄平均配速、總距離與趟數

### 4.5 其他運動模式

官方列出的運動類型還包括：
- 步行
- 滑雪與滑雪板
- 室外划船與划槳
- 高爾夫球
- 橢圓機與划船機
- 踏步機
- 高強度間歇訓練（HIIT）
- 瑜伽
- 功能性肌力訓練
- 舞蹈
- 核心訓練
- 皮拉提斯
- 太極拳
- 踢拳
- 輪椅活動

## 5. 健康與保健功能

### 5.1 心率監測

- 光學心率感測器：有，第 2 代
- 心率記錄：有
- 高心率通知：有
- 低心率通知：有
- 心律不整通知：有
- 心率變異相關資料：可透過相應健康功能取得，實際資料呈現依系統功能而異

### 5.2 睡眠監測

- 睡眠追蹤：有
- 睡眠階段：有
- 睡眠分數：有
- 睡眠呼吸中止症通知：有，須符合適用條件與功能可用性規定
- 睡眠相關資料：可搭配 Apple 健康與睡眠 app 查看

### 5.3 體溫與女性健康

- 體溫感測：有
- 經期追蹤：有
- 受孕窗口估計：有
- 排卵日回推估計：有
- 更年期前期與更年期相關提示：有

相關功能的適用條件與資料呈現方式，依 Apple 官方說明為準。

### 5.4 其他健康功能

- 用藥 app：有
- 正念 app：有
- 噪音 app：有
- 生命徵象相關資料：可透過相應 app 查看支援的健康指標

- 心電圖 app：Apple Watch SE 系列不支援此功能。
- 血氧監測：Apple Watch SE 3 的官方技術規格頁未列出血氧監測功能；本資料庫不將未列出的項目直接推定為所有情況下皆不支援。

健康通知與監測功能不能取代專業醫療診斷。實際功能可能受到地區、年齡、系統版本及設定影響。

## 6. 電池與充電

- 電池類型：內建充電式鋰離子電池
- 正常使用續航力：最長 18 小時
- 低耗電模式續航力：最長 32 小時
- 體能訓練追蹤：最長 7 小時
- 快速充電：支援
- 充電約 45 分鐘：最高可達 80% 電量
- 充電 15 分鐘：正常使用最長可達 8 小時
- 充電 8 分鐘：睡眠追蹤最長可達 8 小時

以上均為 Apple 官方公布的最長使用時間或充電條件，實際續航力會因設定、使用方式及環境而異。

## 7. 智慧手錶功能

### 7.1 通訊與連線

- 藍牙：Bluetooth 5.3
- Wi-Fi：支援 2.4GHz Wi-Fi、Wi-Fi 4（802.11n）
- GPS：有
- 行動網路：部分型號支援 LTE
- 手機通知：可與 iPhone 搭配使用
- 全球緊急電話：有，依地區與連線條件而異
- 國際漫遊：支援符合條件的行動網路型號與電信服務

### 7.2 日常智慧功能

- Apple Pay：有
- Siri：有
- 手勢操控：支援雙指互點一下、雙指互點兩下及翻轉手腕
- 尋找 iPhone：有
- 媒體播放：有
- 揚聲器與麥克風：有
- GymKit：有

### 7.3 音樂功能

- 支援媒體播放。
- 可使用相容的音樂 app。
- 音樂串流、離線播放及音樂同步方式依 app、訂閱服務與設定而異。

## 8. 安全功能

- SOS 緊急服務：有
- 全球緊急電話：有
- 跌倒偵測：有
- 車禍偵測：有
- 噪音監測：有
- GPS 回溯：有
- 平安通報：有

部分安全功能須符合裝置設定、網路連線、地區及其他適用條件。

## 9. 防水與耐用性

- 防水等級：50 公尺
- 游泳使用：適用於游泳
- 錶殼材質：鋁金屬
- 螢幕玻璃：Ion-X 玻璃
- 官方抗裂說明：相較於前代 SE 機型，具備 4 倍抗裂能力

防水不代表完全防水或適用所有水上活動，應遵循 Apple 官方使用與保養說明。

## 10. 產品特色

1. **日常智慧功能完整**：整合 iPhone 通知、Apple Pay、Siri、媒體播放及多種 app。
2. **運動種類多元**：涵蓋跑步、健行、自行車、游泳、肌力訓練與瑜伽等活動。
3. **健康監測功能豐富**：具備心率、睡眠、體溫與女性健康相關功能。
4. **隨顯螢幕**：支援常時顯示，方便快速查看時間與資訊。
5. **支援快速充電**：適合日常使用與睡眠追蹤之間安排充電。
6. **安全功能完整**：具備跌倒偵測、車禍偵測及緊急服務等功能。
7. **輕量化設計**：40 公釐 GPS 版本重量為 26.3 公克，適合重視配戴輕便性的使用者。

## 11. 產品限制與注意事項

1. **電池續航時間有限**：正常使用最長 18 小時，與部分強調多日續航的運動手錶相比，可能需要更頻繁充電。
2. **部分健康功能未提供**：SE 3 不支援心電圖 app；官方技術規格頁未列出血氧監測功能。
3. **與 iPhone 搭配使用**：需要相容的 iPhone，無法作為完整獨立於 iPhone 生態系的智慧手錶使用。
4. **行動網路功能有版本差異**：GPS 與 GPS + 行動網路版本的連線能力不同。
5. **健康功能存在適用限制**：部分功能會受地區、年齡、作業系統版本或設定影響。
6. **運動訓練定位**：具備豐富的運動追蹤功能，但選購時仍應依據使用者對續航、訓練分析及專業運動功能的需求進行比較。

## 12. 適合的使用情境

- 日常生活與智慧通知
- 健康及睡眠追蹤
- 一般跑步、健行、自行車與游泳
- 希望使用 Apple Pay 與 iPhone 生態系服務的使用者
- 重視智慧功能、輕便配戴及多元運動紀錄的人

如果主要需求是長時間戶外運動、長距離跑步或多日不充電，建議進一步比較其他運動手錶的續航力與專業訓練功能。

## 13. 官方資料來源

1. Apple Watch SE 3 官方產品介紹：
   https://www.apple.com/tw/apple-watch-se-3/

2. Apple Watch SE 3 官方技術規格：
   https://www.apple.com/tw/apple-watch-se-3/specs/

3. Apple Watch SE 3 官方購買頁面：
   https://www.apple.com/tw/shop/buy-watch/apple-watch-se

4. Apple Watch SE 3 官方技術規格支援頁：
   https://support.apple.com/zh-tw/125094

資料查詢日期：2026-10-28

## 5.第一個可修改函式: 取出 RAG 文字

比如你的文件以 `正文：` 開始，就修改擷取規則。若找不到正文，本函式明確報錯，不擅自把整份文件拿去 embedding。

這個回傳值會原樣保存；未來檢索後也將它交給 LLM，確保搜尋與回答使用同一份內容。

In [ ]:
#定義一個函式，接收原始文字，整理成 RAG 要使用的文字。
def extract_rag_text(raw_text):
    """從 Markdown 文件取得供 RAG 使用的文字。"""
    normalized = (
        raw_text.lstrip("\ufeff")
        .replace("\r\n", "\n")
        .replace("\r", "\n")
    )
    #清除首尾的空白
    body = normalized.strip()

    if not body:
        raise ValueError("文件內容為空，請確認 Markdown 檔案。")

    return body


sample_rag_text = extract_rag_text(sample_raw)

print(sample_rag_text)
print("\n擷取後字元數：", len(sample_rag_text))

# Apple Watch SE 3

## 1. 基本資訊

- 品牌：Apple
- 型號：Apple Watch SE 3
- 推出年份：2025 年
- 產品類型：GPS 智慧手錶
- 官方售價：新台幣 7,900 元起（依錶殼尺寸與連線版本而異，購買前請確認官網價格）
- 錶殼材質：鋁金屬
- 錶殼顏色：午夜色、星光色
- 作業系統：watchOS
- 資料查詢日期：2026-10-28

## 2. 硬體規格

### 2.1 尺寸與重量

**40 公釐版本**
- 錶殼高度：40 公釐
- 錶殼寬度：34 公釐
- 錶殼厚度：10.7 公釐
- 螢幕解析度：324 × 394 像素
- 顯示面積：759 平方公釐
- GPS 版本重量：26.3 公克
- GPS + 行動網路版本重量：26.4 公克
- 適用手腕圍：130–200 公釐

**44 公釐版本**
- 錶殼高度：44 公釐
- 錶殼寬度：38 公釐
- 錶殼厚度：10.7 公釐
- 螢幕解析度：368 × 448 像素
- 顯示面積：977 平方公釐
- GPS 版本重量：32.9 公克
- GPS + 行動網路版本重量：33.0 公克
- 適用手腕圍：140–245 公釐

### 2.2 顯示器

- 顯示器類型：隨顯 Retina 顯示器，採用 OLED 與 LTPO 技術
- 峰值亮度：最高 1,000 尼特
- 最低亮度：2 尼特
- 像素密度：326 ppi
- 螢幕玻璃：Ion-X 玻璃錶面
- 耐用性：官方表示玻璃具備 4 倍抗裂能力

### 2.3 處理器與儲存空間

- 晶片：Apple S10
- 處理器：64 位元雙核心處理器
- 神經網路引擎：4 核心
- 儲存容量：64GB

### 2.4 感測器

- 第 2 代光學心率感測器
- 體溫感測器
- 指南針
- 常啟高度計
- 高 g 值加速度計
- 高動態範圍陀螺儀
- 環境光度感測器

## 3. GPS 與定位功能

- GPS：有
- 定位系統：L1 GPS、GLONASS、Galileo、QZSS、北斗
- 指南針：有
- 高度計：有，採常啟式高度計
- 健行定位：可使用指南針、座標、海拔高度、航點與 GPS 回溯等功能
- 路線功能：支援部分離線地圖及自訂路線功能，實際可用範圍依功能與地區而異

## 4. 運動與訓練功能

### 4.1 跑步功能

- 跑步活動記錄：有
- 自訂訓練：有
- 自訂體能訓練顯示畫面：有
- 訓練負荷：有
- 心率區間：有，可自訂
- 體能訓練後心率：有
- 最大攝氧量（VO₂ max）：有
- 路線競速：有
- 配速員：有
- 自動田徑場偵測：有
- 多運動訓練：有
- 跑步指標：支援步頻、步幅長度、觸地時間、垂直振幅與跑步功率
- 訓練提示：支援心率區間、配速及目標提示

### 4.2 健行功能

- 指南針與方位資訊：有
- 海拔高度及座標：有
- 自訂航點：有
- GPS 回溯：有
- 離線地圖及自訂路線：支援部分相關功能，實際可用性依地區與設定而異

### 4.3 自行車功能

- 記錄平均速度、爬升高度與距離
- 支援透過藍牙連接自行車配件
- 支援功能性閾值功率、功率區間及踏頻
- 可在 iPhone 上顯示即時動態

### 4.4 游泳功能

- 泳池游泳：有
- 開放水域游泳：有
- 自訂泳池游泳訓練：有
- 分段與自動組合：有
- 自動泳式偵測：有
- 浮板偵測：有
- 游泳效率指標（SWOLF）：有
- 記錄平均配速、總距離與趟數

### 4.5 其他運動模式

官方列出的運動類型還包括：
- 步行
- 滑雪與滑雪板
- 室外划船與划槳
- 高爾夫球
- 橢圓機與划船機
- 踏步機
- 高強度間歇訓練（HIIT）
- 瑜伽
- 功能性肌力訓練
- 舞蹈
- 核心訓練
- 皮拉提斯
- 太極拳
- 踢拳
- 輪椅活動

## 5. 健康與保健功能

### 5.1 心率監測

- 光學心率感測器：有，第 2 代
- 心率記錄：有
- 高心率通知：有
- 低心率通知：有
- 心律不整通知：有
- 心率變異相關資料：可透過相應健康功能取得，實際資料呈現依系統功能而異

### 5.2 睡眠監測

- 睡眠追蹤：有
- 睡眠階段：有
- 睡眠分數：有
- 睡眠呼吸中止症通知：有，須符合適用條件與功能可用性規定
- 睡眠相關資料：可搭配 Apple 健康與睡眠 app 查看

### 5.3 體溫與女性健康

- 體溫感測：有
- 經期追蹤：有
- 受孕窗口估計：有
- 排卵日回推估計：有
- 更年期前期與更年期相關提示：有

相關功能的適用條件與資料呈現方式，依 Apple 官方說明為準。

### 5.4 其他健康功能

- 用藥 app：有
- 正念 app：有
- 噪音 app：有
- 生命徵象相關資料：可透過相應 app 查看支援的健康指標

- 心電圖 app：Apple Watch SE 系列不支援此功能。
- 血氧監測：Apple Watch SE 3 的官方技術規格頁未列出血氧監測功能；本資料庫不將未列出的項目直接推定為所有情況下皆不支援。

健康通知與監測功能不能取代專業醫療診斷。實際功能可能受到地區、年齡、系統版本及設定影響。

## 6. 電池與充電

- 電池類型：內建充電式鋰離子電池
- 正常使用續航力：最長 18 小時
- 低耗電模式續航力：最長 32 小時
- 體能訓練追蹤：最長 7 小時
- 快速充電：支援
- 充電約 45 分鐘：最高可達 80% 電量
- 充電 15 分鐘：正常使用最長可達 8 小時
- 充電 8 分鐘：睡眠追蹤最長可達 8 小時

以上均為 Apple 官方公布的最長使用時間或充電條件，實際續航力會因設定、使用方式及環境而異。

## 7. 智慧手錶功能

### 7.1 通訊與連線

- 藍牙：Bluetooth 5.3
- Wi-Fi：支援 2.4GHz Wi-Fi、Wi-Fi 4（802.11n）
- GPS：有
- 行動網路：部分型號支援 LTE
- 手機通知：可與 iPhone 搭配使用
- 全球緊急電話：有，依地區與連線條件而異
- 國際漫遊：支援符合條件的行動網路型號與電信服務

### 7.2 日常智慧功能

- Apple Pay：有
- Siri：有
- 手勢操控：支援雙指互點一下、雙指互點兩下及翻轉手腕
- 尋找 iPhone：有
- 媒體播放：有
- 揚聲器與麥克風：有
- GymKit：有

### 7.3 音樂功能

- 支援媒體播放。
- 可使用相容的音樂 app。
- 音樂串流、離線播放及音樂同步方式依 app、訂閱服務與設定而異。

## 8. 安全功能

- SOS 緊急服務：有
- 全球緊急電話：有
- 跌倒偵測：有
- 車禍偵測：有
- 噪音監測：有
- GPS 回溯：有
- 平安通報：有

部分安全功能須符合裝置設定、網路連線、地區及其他適用條件。

## 9. 防水與耐用性

- 防水等級：50 公尺
- 游泳使用：適用於游泳
- 錶殼材質：鋁金屬
- 螢幕玻璃：Ion-X 玻璃
- 官方抗裂說明：相較於前代 SE 機型，具備 4 倍抗裂能力

防水不代表完全防水或適用所有水上活動，應遵循 Apple 官方使用與保養說明。

## 10. 產品特色

1. **日常智慧功能完整**：整合 iPhone 通知、Apple Pay、Siri、媒體播放及多種 app。
2. **運動種類多元**：涵蓋跑步、健行、自行車、游泳、肌力訓練與瑜伽等活動。
3. **健康監測功能豐富**：具備心率、睡眠、體溫與女性健康相關功能。
4. **隨顯螢幕**：支援常時顯示，方便快速查看時間與資訊。
5. **支援快速充電**：適合日常使用與睡眠追蹤之間安排充電。
6. **安全功能完整**：具備跌倒偵測、車禍偵測及緊急服務等功能。
7. **輕量化設計**：40 公釐 GPS 版本重量為 26.3 公克，適合重視配戴輕便性的使用者。

## 11. 產品限制與注意事項

1. **電池續航時間有限**：正常使用最長 18 小時，與部分強調多日續航的運動手錶相比，可能需要更頻繁充電。
2. **部分健康功能未提供**：SE 3 不支援心電圖 app；官方技術規格頁未列出血氧監測功能。
3. **與 iPhone 搭配使用**：需要相容的 iPhone，無法作為完整獨立於 iPhone 生態系的智慧手錶使用。
4. **行動網路功能有版本差異**：GPS 與 GPS + 行動網路版本的連線能力不同。
5. **健康功能存在適用限制**：部分功能會受地區、年齡、作業系統版本或設定影響。
6. **運動訓練定位**：具備豐富的運動追蹤功能，但選購時仍應依據使用者對續航、訓練分析及專業運動功能的需求進行比較。

## 12. 適合的使用情境

- 日常生活與智慧通知
- 健康及睡眠追蹤
- 一般跑步、健行、自行車與游泳
- 希望使用 Apple Pay 與 iPhone 生態系服務的使用者
- 重視智慧功能、輕便配戴及多元運動紀錄的人

如果主要需求是長時間戶外運動、長距離跑步或多日不充電，建議進一步比較其他運動手錶的續航力與專業訓練功能。

## 13. 官方資料來源

1. Apple Watch SE 3 官方產品介紹：
   https://www.apple.com/tw/apple-watch-se-3/

2. Apple Watch SE 3 官方技術規格：
   https://www.apple.com/tw/apple-watch-se-3/specs/

3. Apple Watch SE 3 官方購買頁面：
   https://www.apple.com/tw/shop/buy-watch/apple-watch-se

4. Apple Watch SE 3 官方技術規格支援頁：
   https://support.apple.com/zh-tw/125094

資料查詢日期：2026-10-28

擷取後字元數： 4242

## 6. 第二個可修改函式：取出 metadata

`extract_metadata(raw_text, filename)` 回傳標題、網址、日期、檔名和文件性質。metadata 是追溯資料用的資訊，不會整包送進 embedding。

**換自己的資料，可在這裡增減欄位。** 例如食譜可以增加料理類型，課程介紹可以增加學期。來源與日期找不到時用 `None`，不自行捏造；標題缺失時使用檔名。

這裡的 `date` 是教材整理日期，不是法規生效日期。保留「教學改寫摘要」的性質，避免後續展示誤稱官方原文。

In [ ]:

def extract_metadata(raw_text, filename):
    """從 Markdown 文件取得描述資訊。"""
    normalized = (
        raw_text.lstrip("\ufeff")
        .replace("\r\n", "\n")
        .replace("\r", "\n")
    )

    def read_field(names):
        for name in names:
            match = re.search(
                rf"^\s*(?:[-*]\s*)?{re.escape(name)}[：:][ \t]*(.*)$",
                normalized,
                flags=re.MULTILINE
            )
            if match and match.group(1).strip():
                return match.group(1).strip()
        return None

    # 讀取第一個一級標題
    title_match = re.search(
        r"^#\s+(.+)$",
        normalized,
        flags=re.MULTILINE
    )
    title = (
        title_match.group(1).strip()
        if title_match
        else Path(filename).stem
    )

    # 讀取文件中第一個網址
    url_match = re.search(
        r"https?://[^\s)\]]+",
        normalized
    )
    source_url = url_match.group(0) if url_match else None

    # 讀取資料查詢日期
    date = read_field([
        "資料查詢日期",
        "教材整理日期",
        "資料整理日期",
        "整理日期"
    ])

    return {
        "title": title,
        "source_url": source_url,
        "date": date,
        "filename": filename,
        "document_type": read_field(["資料類型"]) or "運動手錶產品資料",
    }


sample_metadata = extract_metadata(
    sample_raw,
    sample_path.relative_to(DATA_DIR).as_posix()
)

print(json.dumps(sample_metadata, ensure_ascii=False, indent=2))

{
  "title": "Apple Watch SE 3",
  "source_url": "https://www.apple.com/tw/apple-watch-se-3/",
  "date": "2026-10-28",
  "filename": "AppleWatchSE3.md",
  "document_type": "運動手錶產品資料"
}

## 7. 批次整理成統一格式

把兩個函式組合起來，每篇得到 `doc_id`、`text` 和 `metadata`。檔案先排序，再按順序給編號；只要教材及排序不變，編號便相同。新增文件可能改變編號，因此需要整套重建索引與對照。

請檢查列表中每篇是否有標題、正文及來源。缺少 metadata 會提醒；正文缺失則停止並指出檔名，讓你回到前兩格修改函式。

**將上傳的Markdown運動手錶資料，逐一讀取、擷取正文與metadata，再整理成統一的資料結構，讓後續的embedding和FAISS可以使用。**

**embedding(向量嵌入):是一種將文字、圖片、聲音或商品等資料轉換成一串實數數字（向量）的技術。**

In [ ]:
documents = []
for number, path in enumerate(md_paths, start=1):
    filename = path.relative_to(DATA_DIR).as_posix()
    try:
        raw_text = path.read_text(encoding="utf-8-sig")
        if "\ufffd" in raw_text:
            raise ValueError("文字含有替代字元，請檢查原始編碼。")
        rag_text = extract_rag_text(raw_text)
        metadata = extract_metadata(raw_text, filename)
    except (ValueError, UnicodeDecodeError) as exc:
        raise ValueError(f"處理失敗：{filename}；原因：{exc}") from exc
    documents.append({"doc_id": f"doc_{number:03d}", "text": rag_text, "metadata": metadata})

if not documents:
    raise ValueError("沒有可建立索引的文件。")
index_doc_ids = [doc["doc_id"] for doc in documents]
if len(set(index_doc_ids)) != len(index_doc_ids):
    raise ValueError("doc_id 重複，請檢查編號規則。")

summary = pd.DataFrame([
    {"doc_id": doc["doc_id"], "標題": doc["metadata"]["title"],
     "正文含標題字元數": len(doc["text"]), "來源": doc["metadata"]["source_url"],
     "整理日期": doc["metadata"]["date"]}
    for doc in documents
])
display(summary)
for doc in documents:
    missing = [key for key in ("source_url", "date") if not doc["metadata"].get(key)]
    if missing:
        print("提醒：", doc["doc_id"], "缺少", ", ".join(missing))
print("第一筆統一格式：")
print(json.dumps(documents[0], ensure_ascii=False, indent=2))

,doc_id,標題,正文含標題字元數,來源,整理日期
0,doc_001,Apple Watch SE 3,4242,https://www.apple.com/tw/apple-watch-se-3/,2026-10-28
1,doc_002,COROS PACE 4,4627,https://www.corostw.com/products/pace4-aluminum,2026-10-28
2,doc_003,Polar Pacer,4068,https://www.polar.com/tw-zh/pacer,2026-10-28
3,doc_004,Garmin Forerunner70,3716,https://www.garmin.com.tw/products/wearables/f...,2026-10-28
4,doc_005,Garmin Venu 3,2978,https://www.garmin.com.tw/products/wearables/v...,2026-10-28

第一筆統一格式：
{
  "doc_id": "doc_001",
  "text": "# Apple Watch SE 3\n\n## 1. 基本資訊\n\n- 品牌：Apple\n- 型號：Apple Watch SE 3\n- 推出年份：2025 年\n- 產品類型：GPS 智慧手錶\n- 官方售價：新台幣 7,900 元起（依錶殼尺寸與連線版本而異，購買前請確認官網價格）\n- 錶殼材質：鋁金屬\n- 錶殼顏色：午夜色、星光色\n- 作業系統：watchOS\n- 資料查詢日期：2026-10-28\n\n## 2. 硬體規格\n\n### 2.1 尺寸與重量\n\n**40 公釐版本**\n- 錶殼高度：40 公釐\n- 錶殼寬度：34 公釐\n- 錶殼厚度：10.7 公釐\n- 螢幕解析度：324 × 394 像素\n- 顯示面積：759 平方公釐\n- GPS 版本重量：26.3 公克\n- GPS + 行動網路版本重量：26.4 公克\n- 適用手腕圍：130–200 公釐\n\n**44 公釐版本**\n- 錶殼高度：44 公釐\n- 錶殼寬度：38 公釐\n- 錶殼厚度：10.7 公釐\n- 螢幕解析度：368 × 448 像素\n- 顯示面積：977 平方公釐\n- GPS 版本重量：32.9 公克\n- GPS + 行動網路版本重量：33.0 公克\n- 適用手腕圍：140–245 公釐\n\n### 2.2 顯示器\n\n- 顯示器類型：隨顯 Retina 顯示器，採用 OLED 與 LTPO 技術\n- 峰值亮度：最高 1,000 尼特\n- 最低亮度：2 尼特\n- 像素密度：326 ppi\n- 螢幕玻璃：Ion-X 玻璃錶面\n- 耐用性：官方表示玻璃具備 4 倍抗裂能力\n\n### 2.3 處理器與儲存空間\n\n- 晶片：Apple S10\n- 處理器：64 位元雙核心處理器\n- 神經網路引擎：4 核心\n- 儲存容量：64GB\n\n### 2.4 感測器\n\n- 第 2 代光學心率感測器\n- 體溫感測器\n- 指南針\n- 常啟高度計\n- 高 g 值加速度計\n- 高動態範圍陀螺儀\n- 環境光度感測器\n\n## 3. GPS 與定位功能\n\n- GPS：有\n- 定位系統：L1 GPS、GLONASS、Galileo、QZSS、北斗\n- 指南針：有\n- 高度計：有，採常啟式高度計\n- 健行定位：可使用指南針、座標、海拔高度、航點與 GPS 回溯等功能\n- 路線功能：支援部分離線地圖及自訂路線功能，實際可用範圍依功能與地區而異\n\n## 4. 運動與訓練功能\n\n### 4.1 跑步功能\n\n- 跑步活動記錄：有\n- 自訂訓練：有\n- 自訂體能訓練顯示畫面：有\n- 訓練負荷：有\n- 心率區間：有，可自訂\n- 體能訓練後心率：有\n- 最大攝氧量（VO₂ max）：有\n- 路線競速：有\n- 配速員：有\n- 自動田徑場偵測：有\n- 多運動訓練：有\n- 跑步指標：支援步頻、步幅長度、觸地時間、垂直振幅與跑步功率\n- 訓練提示：支援心率區間、配速及目標提示\n\n### 4.2 健行功能\n\n- 指南針與方位資訊：有\n- 海拔高度及座標：有\n- 自訂航點：有\n- GPS 回溯：有\n- 離線地圖及自訂路線：支援部分相關功能，實際可用性依地區與設定而異\n\n### 4.3 自行車功能\n\n- 記錄平均速度、爬升高度與距離\n- 支援透過藍牙連接自行車配件\n- 支援功能性閾值功率、功率區間及踏頻\n- 可在 iPhone 上顯示即時動態\n\n### 4.4 游泳功能\n\n- 泳池游泳：有\n- 開放水域游泳：有\n- 自訂泳池游泳訓練：有\n- 分段與自動組合：有\n- 自動泳式偵測：有\n- 浮板偵測：有\n- 游泳效率指標（SWOLF）：有\n- 記錄平均配速、總距離與趟數\n\n### 4.5 其他運動模式\n\n官方列出的運動類型還包括：\n- 步行\n- 滑雪與滑雪板\n- 室外划船與划槳\n- 高爾夫球\n- 橢圓機與划船機\n- 踏步機\n- 高強度間歇訓練（HIIT）\n- 瑜伽\n- 功能性肌力訓練\n- 舞蹈\n- 核心訓練\n- 皮拉提斯\n- 太極拳\n- 踢拳\n- 輪椅活動\n\n## 5. 健康與保健功能\n\n### 5.1 心率監測\n\n- 光學心率感測器：有，第 2 代\n- 心率記錄：有\n- 高心率通知：有\n- 低心率通知：有\n- 心律不整通知：有\n- 心率變異相關資料：可透過相應健康功能取得，實際資料呈現依系統功能而異\n\n### 5.2 睡眠監測\n\n- 睡眠追蹤：有\n- 睡眠階段：有\n- 睡眠分數：有\n- 睡眠呼吸中止症通知：有，須符合適用條件與功能可用性規定\n- 睡眠相關資料：可搭配 Apple 健康與睡眠 app 查看\n\n### 5.3 體溫與女性健康\n\n- 體溫感測：有\n- 經期追蹤：有\n- 受孕窗口估計：有\n- 排卵日回推估計：有\n- 更年期前期與更年期相關提示：有\n\n相關功能的適用條件與資料呈現方式，依 Apple 官方說明為準。\n\n### 5.4 其他健康功能\n\n- 用藥 app：有\n- 正念 app：有\n- 噪音 app：有\n- 生命徵象相關資料：可透過相應 app 查看支援的健康指標\n\n- 心電圖 app：Apple Watch SE 系列不支援此功能。\n- 血氧監測：Apple Watch SE 3 的官方技術規格頁未列出血氧監測功能；本資料庫不將未列出的項目直接推定為所有情況下皆不支援。\n\n健康通知與監測功能不能取代專業醫療診斷。實際功能可能受到地區、年齡、系統版本及設定影響。\n\n## 6. 電池與充電\n\n- 電池類型：內建充電式鋰離子電池\n- 正常使用續航力：最長 18 小時\n- 低耗電模式續航力：最長 32 小時\n- 體能訓練追蹤：最長 7 小時\n- 快速充電：支援\n- 充電約 45 分鐘：最高可達 80% 電量\n- 充電 15 分鐘：正常使用最長可達 8 小時\n- 充電 8 分鐘：睡眠追蹤最長可達 8 小時\n\n以上均為 Apple 官方公布的最長使用時間或充電條件，實際續航力會因設定、使用方式及環境而異。\n\n## 7. 智慧手錶功能\n\n### 7.1 通訊與連線\n\n- 藍牙：Bluetooth 5.3\n- Wi-Fi：支援 2.4GHz Wi-Fi、Wi-Fi 4（802.11n）\n- GPS：有\n- 行動網路：部分型號支援 LTE\n- 手機通知：可與 iPhone 搭配使用\n- 全球緊急電話：有，依地區與連線條件而異\n- 國際漫遊：支援符合條件的行動網路型號與電信服務\n\n### 7.2 日常智慧功能\n\n- Apple Pay：有\n- Siri：有\n- 手勢操控：支援雙指互點一下、雙指互點兩下及翻轉手腕\n- 尋找 iPhone：有\n- 媒體播放：有\n- 揚聲器與麥克風：有\n- GymKit：有\n\n### 7.3 音樂功能\n\n- 支援媒體播放。\n- 可使用相容的音樂 app。\n- 音樂串流、離線播放及音樂同步方式依 app、訂閱服務與設定而異。\n\n## 8. 安全功能\n\n- SOS 緊急服務：有\n- 全球緊急電話：有\n- 跌倒偵測：有\n- 車禍偵測：有\n- 噪音監測：有\n- GPS 回溯：有\n- 平安通報：有\n\n部分安全功能須符合裝置設定、網路連線、地區及其他適用條件。\n\n## 9. 防水與耐用性\n\n- 防水等級：50 公尺\n- 游泳使用：適用於游泳\n- 錶殼材質：鋁金屬\n- 螢幕玻璃：Ion-X 玻璃\n- 官方抗裂說明：相較於前代 SE 機型，具備 4 倍抗裂能力\n\n防水不代表完全防水或適用所有水上活動，應遵循 Apple 官方使用與保養說明。\n\n## 10. 產品特色\n\n1. **日常智慧功能完整**：整合 iPhone 通知、Apple Pay、Siri、媒體播放及多種 app。\n2. **運動種類多元**：涵蓋跑步、健行、自行車、游泳、肌力訓練與瑜伽等活動。\n3. **健康監測功能豐富**：具備心率、睡眠、體溫與女性健康相關功能。\n4. **隨顯螢幕**：支援常時顯示，方便快速查看時間與資訊。\n5. **支援快速充電**：適合日常使用與睡眠追蹤之間安排充電。\n6. **安全功能完整**：具備跌倒偵測、車禍偵測及緊急服務等功能。\n7. **輕量化設計**：40 公釐 GPS 版本重量為 26.3 公克，適合重視配戴輕便性的使用者。\n\n## 11. 產品限制與注意事項\n\n1. **電池續航時間有限**：正常使用最長 18 小時，與部分強調多日續航的運動手錶相比，可能需要更頻繁充電。\n2. **部分健康功能未提供**：SE 3 不支援心電圖 app；官方技術規格頁未列出血氧監測功能。\n3. **與 iPhone 搭配使用**：需要相容的 iPhone，無法作為完整獨立於 iPhone 生態系的智慧手錶使用。\n4. **行動網路功能有版本差異**：GPS 與 GPS + 行動網路版本的連線能力不同。\n5. **健康功能存在適用限制**：部分功能會受地區、年齡、作業系統版本或設定影響。\n6. **運動訓練定位**：具備豐富的運動追蹤功能，但選購時仍應依據使用者對續航、訓練分析及專業運動功能的需求進行比較。\n\n## 12. 適合的使用情境\n\n- 日常生活與智慧通知\n- 健康及睡眠追蹤\n- 一般跑步、健行、自行車與游泳\n- 希望使用 Apple Pay 與 iPhone 生態系服務的使用者\n- 重視智慧功能、輕便配戴及多元運動紀錄的人\n\n如果主要需求是長時間戶外運動、長距離跑步或多日不充電，建議進一步比較其他運動手錶的續航力與專業訓練功能。\n\n## 13. 官方資料來源\n\n1. Apple Watch SE 3 官方產品介紹：\n   https://www.apple.com/tw/apple-watch-se-3/\n\n2. Apple Watch SE 3 官方技術規格：\n   https://www.apple.com/tw/apple-watch-se-3/specs/\n\n3. Apple Watch SE 3 官方購買頁面：\n   https://www.apple.com/tw/shop/buy-watch/apple-watch-se\n\n4. Apple Watch SE 3 官方技術規格支援頁：\n   https://support.apple.com/zh-tw/125094\n\n資料查詢日期：2026-10-28",
  "metadata": {
    "title": "Apple Watch SE 3",
    "source_url": "https://www.apple.com/tw/apple-watch-se-3/",
    "date": "2026-10-28",
    "filename": "AppleWatchSE3.md",
    "document_type": "運動手錶產品資料"
  }
}

## 8. 載入 EmbeddingGemma 2

先查詢模型目前的確切版本（commit），再載入該版本，將版本記錄到輸出設定，方便第二份 Colab 使用相同模型。只啟用文字部分，使用適合裝置的精度。

首次下載需要等待。本步使用公開模型，不讀取 Groq 或其他密鑰。若下載失敗，先確認網路；模型架構不受支援時，確認安裝格已完成，並重新啟動工作階段。程式不會默默改用別的模型。

In [ ]:
try:
    MODEL_REVISION = HfApi().model_info(MODEL_ID, token=False).sha
    model = SentenceTransformer(
        MODEL_ID,
        revision=MODEL_REVISION,
        token=False,
        device=DEVICE,
        config_kwargs={"vision_config": None, "audio_config": None},
        model_kwargs={"dtype": DTYPE, "attn_implementation": "eager"},
    )
except Exception as exc:
    raise RuntimeError(
        "EmbeddingGemma 2 載入失敗。請確認網路、套件版本，必要時重新啟動工作階段；"
        "若 GPU 記憶體不足，改用 CPU。未替換成其他模型。"
    ) from exc

print("模型：", MODEL_ID)
print("版本：", MODEL_REVISION)
print("裝置：", model.device)
print("模型精度：", model.dtype)
print("向量維度：", model.get_sentence_embedding_dimension())
print("模型單筆 token 上限：", model.max_seq_length)

modules.json:   0%|          | 0.00/413 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/1.56k [00:00<?, ?B/s]

README.md:   0%|          | 0.00/22.2k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

sentence_bert_config.json:   0%|          | 0.00/747 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/4.46k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.49GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/413 [00:00<?, ?it/s]

processor_config.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/1.02k [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/511 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 32.2MB

tokenizer.json: downloading bytes:           |  0.00B

config.json:   0%|          | 0.00/90.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/97.0 [00:00<?, ?B/s]

模型： google/embeddinggemma-2
版本： f9972ac22e696a105c482202646979e33e4b5a1e
裝置： cuda:0
模型精度： torch.bfloat16
向量維度： 768
模型單筆 token 上限： 1000000000000000019884624838656

/tmp/ipykernel_677/465943176.py:21: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("向量維度：", model.get_sentence_embedding_dimension())

## 9. 檢查輸入長度，避免靜默截斷

本模型採用不同的任務前綴來區分文件和問題。文件本身已有標題，所以組成 `title: none | text: {text}`；問題則用 `task: search result | query: {question}`。

下格計算實際送入模型的文件文字（含前綴）長度。超過上限便停止，不會只取前半段。換成長文件時，可以在後續課程加入 chunking，或重新設計文件單位。

**由於第一次執行時，發現上傳的五個檔案Token數超過設定上限，GPT建議在每份產品說明加入文字切分(chunking)，拆成較小的區塊，再讓每個區塊分別產生向量(embedding)。**

In [ ]:

# 1. 設定文字切分參數
CHUNK_SIZE = 1800
CHUNK_OVERLAP = 100 #在切分區塊時，單獨閱讀第二段，可能缺少前面的主詞或條件，造成上下文斷裂的問題，為了避免故加上重疊。

# 2. 檢查切分參數
if CHUNK_SIZE <= CHUNK_OVERLAP or CHUNK_OVERLAP < 0:
    raise ValueError("切分大小必須大於重疊大小，且重疊大小不可小於 0。")

# 3. 將每份完整文件切分成多個區塊
chunked_documents = []

for doc in documents:
    text = doc["text"]

    # 先將文字轉成 Token ID，不加入特殊 Token
    token_ids = model.tokenizer.encode(
        text,
        add_special_tokens=False
    )

    start = 0
    chunk_number = 1

    while start < len(token_ids):
        end = min(start + CHUNK_SIZE, len(token_ids))

        # 將這一段 Token 還原成文字
        chunk_text = model.tokenizer.decode(
            token_ids[start:end],
            skip_special_tokens=True
        )

        # 每個區塊保留產品標題，增加檢索時的上下文
        title = doc["metadata"]["title"]
        chunk_text = f"產品名稱：{title}\n\n{chunk_text}"

        chunked_documents.append({
            "doc_id": f"{doc['doc_id']}_chunk_{chunk_number:03d}",
            "text": chunk_text,
            "metadata": {
                **doc["metadata"],
                "chunk_number": chunk_number,
                "source_doc_id": doc["doc_id"]
            }
        })

        chunk_number += 1

        if end == len(token_ids):
            break

        # 保留部分前一區塊的內容，減少切分造成的上下文斷裂
        start = end - CHUNK_OVERLAP

# 4. 以切分後的文件取代原本的文件清單
documents = chunked_documents

# 5. 重新建立文件 ID 清單
index_doc_ids = [doc["doc_id"] for doc in documents]

print("原始文件數：5")
print("切分後的區塊數：", len(documents))
print("第一個區塊：")
print(documents[0]["text"][:500])

原始文件數：5
切分後的區塊數： 10
第一個區塊：
產品名稱：Apple Watch SE 3

# Apple Watch SE 3

## 1. 基本資訊

- 品牌：Apple
- 型號：Apple Watch SE 3
- 推出年份：2025 年
- 產品類型：GPS 智慧手錶
- 官方售價：新台幣 7,900 元起（依錶殼尺寸與連線版本而異，購買前請確認官網價格）
- 錶殼材質：鋁金屬
- 錶殼顏色：午夜色、星光色
- 作業系統：watchOS
- 資料查詢日期：2026-10-28

## 2. 硬體規格

### 2.1 尺寸與重量

**40 公釐版本**
- 錶殼高度：40 公釐
- 錶殼寬度：34 公釐
- 錶殼厚度：10.7 公釐
- 螢幕解析度：324 × 394 像素
- 顯示面積：759 平方公釐
- GPS 版本重量：26.3 公克
- GPS + 行動網路版本重量：26.4 公克
- 適用手腕圍：130–200 公釐

**44 公釐版本**
- 錶殼高度：44 公釐
- 錶殼寬度：38 公釐
- 錶殼厚度：10.7 公釐
- 螢幕解析度：368 × 448 像素
- 顯示面積：977 平方公釐
- GP

In [ ]:
document_inputs = [DOCUMENT_TEMPLATE.format(text=doc["text"]) for doc in documents]
TOKEN_LIMIT = min(2048, int(model.max_seq_length))

if TOKEN_LIMIT <= 0:
    raise ValueError("輸入長度上限必須大於0。")

def count_input_tokens(text):
    return len(model.tokenizer(text, add_special_tokens=True, truncation=False)["input_ids"])

token_counts = [count_input_tokens(text) for text in document_inputs]
length_table = pd.DataFrame({"doc_id": index_doc_ids, "tokens_含前綴": token_counts})
display(length_table)
long_docs = [doc_id for doc_id, length in zip(index_doc_ids, token_counts) if length > TOKEN_LIMIT]
if long_docs:
    raise ValueError(f"以下文件超過 {TOKEN_LIMIT} tokens，請先調整資料：{long_docs}")
print("本教材使用的 token 上限：", TOKEN_LIMIT)
print("全部文件均未超過上限；不需要截斷。")
print("第一筆真正送入 embedding 的文字：\n", document_inputs[0])

              doc_id  tokens_含前綴
0  doc_001_chunk_001        1818
1  doc_001_chunk_002        1190
2  doc_002_chunk_001        1818
3  doc_002_chunk_002        1403
4  doc_003_chunk_001        1816
5  doc_003_chunk_002         775
6  doc_004_chunk_001        1819
7  doc_004_chunk_002         978
8  doc_005_chunk_001        1819
9  doc_005_chunk_002         445

本教材使用的 token 上限： 2048
全部文件均未超過上限；不需要截斷。
第一筆真正送入 embedding 的文字：
 title: none | text: 產品名稱：Apple Watch SE 3

# Apple Watch SE 3

## 1. 基本資訊

- 品牌：Apple
- 型號：Apple Watch SE 3
- 推出年份：2025 年
- 產品類型：GPS 智慧手錶
- 官方售價：新台幣 7,900 元起（依錶殼尺寸與連線版本而異，購買前請確認官網價格）
- 錶殼材質：鋁金屬
- 錶殼顏色：午夜色、星光色
- 作業系統：watchOS
- 資料查詢日期：2026-10-28

## 2. 硬體規格

### 2.1 尺寸與重量

**40 公釐版本**
- 錶殼高度：40 公釐
- 錶殼寬度：34 公釐
- 錶殼厚度：10.7 公釐
- 螢幕解析度：324 × 394 像素
- 顯示面積：759 平方公釐
- GPS 版本重量：26.3 公克
- GPS + 行動網路版本重量：26.4 公克
- 適用手腕圍：130–200 公釐

**44 公釐版本**
- 錶殼高度：44 公釐
- 錶殼寬度：38 公釐
- 錶殼厚度：10.7 公釐
- 螢幕解析度：368 × 448 像素
- 顯示面積：977 平方公釐
- GPS 版本重量：32.9 公克
- GPS + 行動網路版本重量：33.0 公克
- 適用手腕圍：140–245 公釐

### 2.2 顯示器

- 顯示器類型：隨顯 Retina 顯示器，採用 OLED 與 LTPO 技術
- 峰值亮度：最高 1,000 尼特
- 最低亮度：2 尼特
- 像素密度：326 ppi
- 螢幕玻璃：Ion-X 玻璃錶面
- 耐用性：官方表示玻璃具備 4 倍抗裂能力

### 2.3 處理器與儲存空間

- 晶片：Apple S10
- 處理器：64 位元雙核心處理器
- 神經網路引擎：4 核心
- 儲存容量：64GB

### 2.4 感測器

- 第 2 代光學心率感測器
- 體溫感測器
- 指南針
- 常啟高度計
- 高 g 值加速度計
- 高動態範圍陀螺儀
- 環境光度感測器

## 3. GPS 與定位功能

- GPS：有
- 定位系統：L1 GPS、GLONASS、Galileo、QZSS、北斗
- 指南針：有
- 高度計：有，採常啟式高度計
- 健行定位：可使用指南針、座標、海拔高度、航點與 GPS 回溯等功能
- 路線功能：支援部分離線地圖及自訂路線功能，實際可用範圍依功能與地區而異

## 4. 運動與訓練功能

### 4.1 跑步功能

- 跑步活動記錄：有
- 自訂訓練：有
- 自訂體能訓練顯示畫面：有
- 訓練負荷：有
- 心率區間：有，可自訂
- 體能訓練後心率：有
- 最大攝氧量（VO₂ max）：有
- 路線競速：有
- 配速員：有
- 自動田徑場偵測：有
- 多運動訓練：有
- 跑步指標：支援步頻、步幅長度、觸地時間、垂直振幅與跑步功率
- 訓練提示：支援心率區間、配速及目標提示

### 4.2 健行功能

- 指南針與方位資訊：有
- 海拔高度及座標：有
- 自訂航點：有
- GPS 回溯：有
- 離線地圖及自訂路線：支援部分相關功能，實際可用性依地區與設定而異

### 4.3 自行車功能

- 記錄平均速度、爬升高度與距離
- 支援透過藍牙連接自行車配件
- 支援功能性閾值功率、功率區間及踏頻
- 可在 iPhone 上顯示即時動態

### 4.4 游泳功能

- 泳池游泳：有
- 開放水域游泳：有
- 自訂泳池游泳訓練：有
- 分段與自動組合：有
- 自動泳式偵測：有
- 浮板偵測：有
- 游泳效率指標（SWOLF）：有
- 記錄平均配速、總距離與趟數

### 4.5 其他運動模式

官方列出的運動類型還包括：
- 步行
- 滑雪與滑雪板
- 室外划船與划槳
- 高爾夫球
- 橢圓機與划船機
- 踏步機
- 高強度間歇訓練（HIIT）
- 瑜伽
- 功能性肌力訓練
- 舞蹈
- 核心訓練
- 皮拉提斯
- 太極拳
- 踢拳
- 輪椅活動

## 5. 健康與保健功能

### 5.1 心率監測

- 光學心率感測器：有，第 2 代
- 心率記錄：有
- 高心率通知：有
- 低心率通知：有
- 心律不整通知：有
- 心率變異相關資料：可透過相應健康功能取得，實際資料呈現依系統功能而異

### 5.2 睡眠監測

- 睡眠追蹤：有
- 睡眠階段：有
- 睡眠分數：有
- 睡眠呼吸中止症通知：有，須符合適用條件與功能可用性規定
- 睡眠相關資料：可搭配 Apple 健康與睡眠 app 查看

### 5.3 體溫與女性健康

- 體溫感測：有
- 經期追蹤：有
- 受孕窗口估計：有
- 排卵日回推估計：有
- 更年期前期與更年期相關提示：有

相關功能的適用條件與資料呈現方式，依 Apple 官方說明為準。

### 5.4 其他健康功能

- 用藥 app：有
- 正念 app：有
- 噪音 app：有
- 生命徵象相關資料：可透過相應 app 查看支援的健康指標

- 心電圖 app：Apple Watch SE 系列不支援此功能。
- 血氧監測：Apple Watch SE 3 的官方技術規格頁未列出血氧監測功能；本資料庫不將未列出的項目直接推定為所有情況下皆不支援。

健康通知與監測功能不能取代專業醫療診斷。實際功能可能受到地區、年齡、系統版本及設定影響。

## 6. 電池與充電

- 電池類型：內建充電式鋰離子電池
- 正常使用續航力：最長 18 小時
- 低耗電模式續航力：最長 32 小時
- 體能訓練追蹤：最長 7 小時
- 快速充電：支援
- 充電約 45 分鐘：最高可達 80% 電量
- 充電 15 分鐘：正常使用最長可達 8 小時
- 充電 8 分鐘：睡眠追蹤最長可達 8 小時

以上均為 Apple 官方公布的最長使用時間或充電條件，實際續航力會因設定、使用方式及環境而異。

## 7. 智慧手錶功能

### 7.1 通訊與連線

- 藍牙：Bluetooth 5.3
- Wi-

## 10. 產生並觀察文件向量

一篇文件對應矩陣中的一列，欄數是向量維度。`prompt=""` 表示前綴已自行加入，不讓模型額外再加一次。

向量正規化後長度約為1，內積便等於 cosine similarity。下格也將資料轉為 FAISS 使用的 float32 連續陣列，檢查空向量、非有限值及形狀。

**將前面切分好的文件區塊轉換成數值向量（Embedding），並檢查向量是否正常。**

In [ ]:
embeddings = model.encode(
    document_inputs,
    prompt="",
    batch_size=BATCH_SIZE, #每批處理幾筆文字
    convert_to_numpy=True, #將結果轉成NumPy陣列
    normalize_embeddings=True, #將輸出的向量正規化
    show_progress_bar=True,
)
embeddings = np.ascontiguousarray(embeddings, dtype=np.float32)
if embeddings.ndim != 2 or embeddings.shape[0] != len(documents):
    raise ValueError("向量形狀與文件數不符。")
if not np.isfinite(embeddings).all():
    raise ValueError("向量含有 NaN 或無限值。")
if np.any(np.linalg.norm(embeddings, axis=1) <= 0):
    raise ValueError("出現零向量。")
faiss.normalize_L2(embeddings)
DIMENSION = int(embeddings.shape[1])
if DIMENSION != int(model.get_sentence_embedding_dimension()):
    raise ValueError("實際向量維度與模型宣告不符。")
print("矩陣形狀（文件數, 向量維度）：", embeddings.shape)
print("第一篇向量的前10個數字：", embeddings[0, :10])
print("前5篇向量長度：", np.linalg.norm(embeddings[:5], axis=1))

Batches:   0%|          | 0/3 [00:00<?, ?it/s]

矩陣形狀（文件數, 向量維度）： (10, 768)
第一篇向量的前10個數字： [ 0.03293969 -0.00323297 -0.04928754 -0.00469696 -0.01006491  0.04465158
  0.01421287 -0.03611166 -0.00253148 -0.12785481]
前5篇向量長度： [1.        1.0000001 1.        1.        1.       ]

/tmp/ipykernel_677/119107976.py:18: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  if DIMENSION != int(model.get_sentence_embedding_dimension()):

## 11. 建立 FAISS 精確搜尋索引

`IndexFlatIP` 比較問題向量與所有文件向量的內積。因為雙方都正規化，排名就是 cosine similarity 的排名。

FAISS 回傳的是向量編號，**不是原文**。`index_doc_ids` 保存向量順序與文件編號的對應，再透過 `doc_id` 找回正文與 metadata。

In [ ]:
index = faiss.IndexFlatIP(DIMENSION)
index.add(embeddings)
documents_by_id = {doc["doc_id"]: doc for doc in documents}
assert index.ntotal == len(index_doc_ids) == len(documents)
print("索引類型：", type(index).__name__)
print("索引向量數：", index.ntotal)
print("索引維度：", index.d)
display(pd.DataFrame({"FAISS編號": range(len(index_doc_ids)), "doc_id": index_doc_ids}))

索引類型： IndexFlatIP
索引向量數： 10
索引維度： 768

   FAISS編號             doc_id
0        0  doc_001_chunk_001
1        1  doc_001_chunk_002
2        2  doc_002_chunk_001
3        3  doc_002_chunk_002
4        4  doc_003_chunk_001
5        5  doc_003_chunk_002
6        6  doc_004_chunk_001
7        7  doc_004_chunk_002
8        8  doc_005_chunk_001
9        9  doc_005_chunk_002

## 12. 定義問題向量化與搜尋函式

問題也要用同一個 embedding 模型向量化，但使用查詢專用前綴。`top_k` 表示取回幾篇文件；程式限制它不超過實際文件數。

搜尋函式只做檢索，還沒有呼叫 LLM。精確搜尋保證依目前向量找到分數最高者，不保證文件一定足以回答問題。

In [ ]:
#將user的問題轉成向量
def embed_question(question):
    if not isinstance(question, str) or not question.strip():
        raise ValueError("請輸入非空白問題。")
    query_input = QUERY_TEMPLATE.format(question=question.strip())
    if count_input_tokens(query_input) > TOKEN_LIMIT:
        raise ValueError("問題超過模型輸入長度上限，請縮短問題。")
    query_vector = model.encode(
        [query_input], prompt="", convert_to_numpy=True,
        normalize_embeddings=True, show_progress_bar=False,
    )
    query_vector = np.ascontiguousarray(query_vector, dtype=np.float32)
    if query_vector.shape != (1, DIMENSION) or not np.isfinite(query_vector).all():
        raise ValueError("問題向量的維度或數值不正確。")
    if np.linalg.norm(query_vector) <= 0:
        raise ValueError("問題產生零向量。")
    #確認向量維度正確後進行正規化
    faiss.normalize_L2(query_vector)
    return query_vector

#用問題向量搜尋最相關的文件區塊
#top_k=n，表示預設取出n個最相關的文件區塊
def search_documents(question, top_k=1):
    if isinstance(top_k, bool) or not isinstance(top_k, (int, np.integer)) or top_k < 1:
        raise ValueError("top_k 必須是大於0的整數。")
    query_vector = embed_question(question)
    scores, positions = index.search(query_vector, min(int(top_k), index.ntotal))
    results = []
    for rank, (position, score) in enumerate(zip(positions[0], scores[0]), start=1):
        doc_id = index_doc_ids[int(position)]
        results.append({"rank": rank, "score": float(score), **documents_by_id[doc_id]})
    return results

## 13. 試查一次，閱讀真正取回的內容

修改 `QUESTION` 和 `TOP_K`，重新執行本格即可查詢。先看標題及分數，再讀完整正文，判斷是否有足夠依據。

可以比較 `top_k=1`、`3`、`5`。。**相似度不是正確率，也不是模型有答案的機率。**

In [ ]:
QUESTION = "哪個手錶的電池續航力最好?"
TOP_K = 1
results = search_documents(QUESTION, TOP_K)
display(pd.DataFrame([
    {"排名": r["rank"], "doc_id": r["doc_id"], "標題": r["metadata"]["title"],
     "cosine_similarity": r["score"], "來源": r["metadata"]["source_url"]}
    for r in results
]))
for result in results:
    print(f"\n[{result['doc_id']}] {result['metadata']['title']} ({result['score']:.4f})")
    print(result["text"])
    print("來源：", result["metadata"]["source_url"] or "未提供")

,排名,doc_id,標題,cosine_similarity,來源
0,1,doc_003_chunk_001,Polar Pacer,0.724452,https://www.polar.com/tw-zh/pacer

[doc_003_chunk_001] Polar Pacer (0.7245)
產品名稱：Polar Pacer

# Polar Pacer


## 1. 基本資料

- **產品名稱：** Polar Pacer
- **品牌：** Polar
- **產品類型：** GPS 運動手錶
- **產品定位：** 以跑步與日常運動訓練為主，提供 GPS 定位、手腕式心率追蹤、訓練分析、睡眠與恢復功能。
- **台灣官方產品頁標示價格：** NT$7,700；價格可能變動。
- **錶殼尺寸：** 45 × 45 × 11.5 mm
- **重量：** 含腕帶 40 g；不含腕帶 23 g
- **防水等級：** WR50
- **官方產品頁展示顏色：** Night Black（夜黑色）
-   資料查詢日期：2026-10-28
- **官方產品頁：** https://www.polar.com/tw-zh/pacer

## 2. 硬體與技術規格

### 2.1 螢幕與外觀

- **螢幕類型：** MIP（Memory-in-Pixel）顯示器
- **螢幕尺寸：** 1.2 吋
- **解析度：** 240 × 240 像素
- **常時顯示：** 支援
- **螢幕材質：** Gorilla Glass
- **錶殼材質：** 塑膠
- **操作溫度：** -10°C 至 +50°C
- **防水：** WR50；請依官方防水使用說明操作，不應直接視為可用於所有水上活動。

### 2.2 處理效能與儲存空間

- **CPU 速度：** 192 MHz
- **記憶體：** 5 MB
- **儲存空間：** 32 MB

### 2.3 定位與連線

- **內建定位：** 有
- **支援衛星定位系統：** GPS、GLONASS、Galileo、QZSS
- **輔助定位：** A-GPS、A-GLONASS、A-Galileo、A-QZSS
- **藍牙：** Bluetooth Low Energy（低功耗藍牙）
- **充電／資料傳輸線：** 專用 USB-A 連接線
- **手機通知：** 支援推送通知
- **音樂控制：** 支援控制連線手機上的音樂；不代表手錶可獨立儲存或播放音樂。
- **天氣：** 支援天氣資訊功能
- **資料平台：** Polar Flow App 與網頁服務，可同步、查看及分析活動與訓練資料。

### 2.4 感測器

- **手腕式光學心率：** Polar Precision Prime™，Gen 3.5 光學心率感測器
- **加速度計：** 有
- **心電圖（ECG）：** 官方規格標示無
- **血氧飽和度測量：** 官方規格標示無
- **皮膚溫度感測：** 官方規格標示無

## 3. 運動與訓練功能

### 3.1 跑步與訓練分析

- 記錄跑步與其他運動的訓練資料，包括配速、時間、距離及心率等相關指標。
- **Running Index（跑步指數）：** 協助觀察跑步表現與有氧跑步能力的變化。
- **跑步計劃：** 可透過 Polar Flow 建立或使用跑步訓練計劃。
- **訓練目標：** 可設定訓練目標。
- **訓練課程規劃：** 提供季度規劃器等訓練規劃工具。
- **跑步表現測試：** 提供跑步表現相關測試。
- **有氧健康測試：** 提供有氧體能相關測試。
- **步行測試：** 提供步行測試功能。
- **FitSpark®：** 提供依個人狀況安排的每日訓練建議。
- **Training Load Pro™：** 協助分析訓練負荷，了解訓練對身體造成的負擔。
- **語音指導：** 支援訓練期間的語音指導功能；使用條件可能依手機與 App 設定而異。

### 3.2 其他運動

- **運動模式數量：** Polar 官方產品頁表示可在 Polar Flow 中選擇 150 種以上的運動內容。
- **游泳：** 支援游泳指標。
- 可在 Polar Flow 選擇不同運動項目，並為相應運動顯示專屬資料畫面與訓練指標。
- 實際可選運動類型與可記錄指標，依手錶設定、韌體與 Polar Flow 的支援內容而異。

### 3.3 訓練時間工具

- 秒錶：有
- 倒數計時器：有
- 間隔計時器：有
- 手動記圈：有
- 自動記圈：有
- 自動啟停：有
- 配速顯示：有
- 振動提示：有

## 4. 日常活動與健康追蹤

- **全天候活動追蹤：** 有
- **步數追蹤：** 有
- **活動目標：** 有
- **不活躍提示：** 有
- **活動效益：** 有
- **卡路里估算：** 有
- **全天候心率監測：** 有
- **心率感測方式：** 手腕式光學心率感測器

> 心率與卡路里等數值屬於穿戴裝置的估算或測量結果，不應直接取代醫療設備或專業醫療判斷。

## 5. 睡眠與恢復功能

- **Sleep Plus Stages™：** 分析睡眠時間與睡眠階段。
- **Nightly Recharge™：** 評估夜間恢復狀況。
- **SleepWise™：** 提供與白天警覺度相關的睡眠洞察。
- **Serene™：** 提供呼吸練習功能。
- **恢復工具：** 結合睡眠與訓練資訊，協助使用者觀察恢復狀態。

## 6. 戶外與導航功能

- **返回起點：** 有，可協助使用者沿路線返回起點。
- **日光時間資訊：** 有。
- **GPS 定位：** 有，支援多種全球導航衛星系統。
- 官方產品頁列有戶外與導航功能，但不應因此推定手錶具備完整離線地圖或逐轉導航；若比較導航能力，應以官方明確列出的功能為準。

## 7. 電池與續航力

- **電池容量：** 265 mAh
- **電池類型：** 鋰聚合物充電電池
- **官方產品頁標示的高性能訓練模式：** 最長 32 小時
- **官方產品頁標示的節能訓練模式：** 最長 155 小時
- **官方產品頁標示的智慧手錶模式：** 最長 6.5 天

**續航資料注意事項：** Polar 的使用手冊另列出訓練模式最長 35 小時、啟用持續心率追蹤的手錶模式最長 7 天，以及省電設定下訓練模式最長 100 小時等數值。不同頁面可能採用不同測試條件或規格版本，因此本文件優先保留使用者指定的產品頁所列數值；若要進行嚴格的產品比較，應統一採用相同官方文件與測試條件。

## 8. 日常智慧功能

- 推送通知：有
- 手機音樂控制：有
- 天氣資訊：有
- 鬧鐘：有
- 時鐘與日期顯示：有
- 背光燈：有
- 按鍵鎖：有
- 韌體更新：有

**功能界線：** Polar Pacer 的定位以運動、訓練、活動、睡眠與恢復追蹤為主。官方產品頁列出的是手機音樂控制，而非手錶獨立音樂儲存／播放功能。產品頁亦未列出 ECG、血氧飽和度或皮膚溫度感測功能。

## 9. 產品特色摘要

1. **以跑步訓練為核心：
來源： https://www.polar.com/tw-zh/pacer

## 14. 保存索引、文件、編號對照與設定

第二份 Colab 需要下面四個檔案，不能只拿 FAISS 索引：

| 檔案 | 用途 |
|---|---|
| `index.faiss` | 文件向量與搜尋索引 |
| `documents.json` | 取回後提供給 LLM 的正文與來源資訊 |
| `index_doc_ids.json` | FAISS 編號對應的文件編號 |
| `config.json` | 模型確切版本、前綴、維度、正規化、套件版本及檢查資訊 |

不保存模型權重、API 金鑰或其他環境變數。第二份 Colab 載入相同模型版本，只重新計算問題向量。

In [ ]:

# 1. 建立保存資料的資料夾
EXPORT_DIR = Path(tempfile.mkdtemp(prefix="rag_index_"))

# 2. 保存 FAISS 索引
faiss.write_index(index, str(EXPORT_DIR / "index.faiss"))

# 3. 保存 Chunk 文字與索引編號對照
for filename, data in [
    ("documents.json", documents),
    ("index_doc_ids.json", index_doc_ids),
]:
    (EXPORT_DIR / filename).write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8"
    )

# 4. 保存知識庫設定
config = {
    "format_version": "1.0",
    "created_at": datetime.now(
        ZoneInfo("Asia/Taipei")
    ).isoformat(timespec="seconds"),

    "model_id": MODEL_ID,
    "model_revision": MODEL_REVISION,
    "model_config_kwargs": {
        "vision_config": None,
        "audio_config": None
    },

    "dimension": DIMENSION,
    "normalize_embeddings": True,
    "index_type": "IndexFlatIP",
    "metric": "cosine_similarity_via_normalized_inner_product",

    "document_template": DOCUMENT_TEMPLATE,
    "query_template": QUERY_TEMPLATE,
    "encode_prompt": "",
    "max_seq_length": TOKEN_LIMIT,

    # 目前是一個 Chunk 對應一個向量
    "document_count": len(documents),
    "document_unit": "one_chunk_one_vector",
    "document_text_includes_title": True,

    "package_versions": PACKAGE_VERSIONS,
    "build_device": DEVICE,
    "build_dtype": str(DTYPE),

    # 記錄原始文件數量及來源檔名
    "source_document_count": len({
        doc["metadata"].get("source_doc_id", doc["doc_id"])
        for doc in documents
    }),
    "source_files": sorted({
        doc["metadata"]["filename"]
        for doc in documents
        if doc["metadata"].get("filename")
    }),

    # 計算已保存檔案的 SHA-256
    "file_sha256": {
        name: hashlib.sha256(
            (EXPORT_DIR / name).read_bytes()
        ).hexdigest()
        for name in [
            "index.faiss",
            "documents.json",
            "index_doc_ids.json"
        ]
    },
}

(EXPORT_DIR / "config.json").write_text(
    json.dumps(config, ensure_ascii=False, indent=2),
    encoding="utf-8"
)

# 5. 顯示保存結果
print("知識庫已保存至：", EXPORT_DIR)
print("\n已保存檔案：")

for path in sorted(EXPORT_DIR.iterdir()):
    print(f"{path.name} ({path.stat().st_size:,} bytes)")

print("\n文件區塊數：", len(documents))
print("索引向量數：", index.ntotal)
print("向量維度：", DIMENSION)
print("模型版本及前綴已寫入 config.json。")

知識庫已保存至： /tmp/rag_index_xt42e_k0

已保存檔案：
config.json (1,431 bytes)
documents.json (48,376 bytes)
index.faiss (30,765 bytes)
index_doc_ids.json (232 bytes)

文件區塊數： 10
索引向量數： 10
向量維度： 768
模型版本及前綴已寫入 config.json。

## 15. 重新載入，驗證第二份 Colab 所需的資料

從剛才保存的檔案重新載入，檢查完整性、文件編號與向量對應，再使用**同一個問題向量**比對保存前後的排名與分數。此處不重算問題向量，以免不同運算裝置的細微浮點誤差干擾索引保存檢查。

也將 FAISS 結果與 NumPy 的全矩陣內積排序比較，確認精確搜尋的意義。遇到完全同分時，兩套工具的同分排列順序可以不同。

In [ ]:
loaded_config = json.loads((EXPORT_DIR / "config.json").read_text(encoding="utf-8"))
for name, expected_hash in loaded_config["file_sha256"].items():
    actual_hash = hashlib.sha256((EXPORT_DIR / name).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f"檔案完整性檢查失敗：{name}"

loaded_index = faiss.read_index(str(EXPORT_DIR / "index.faiss"))
loaded_documents = json.loads((EXPORT_DIR / "documents.json").read_text(encoding="utf-8"))
loaded_ids = json.loads((EXPORT_DIR / "index_doc_ids.json").read_text(encoding="utf-8"))
assert loaded_index.ntotal == len(loaded_documents) == len(loaded_ids) == loaded_config["document_count"]
assert loaded_index.d == loaded_config["dimension"]
assert len(set(loaded_ids)) == len(loaded_ids)
assert set(loaded_ids) == {doc["doc_id"] for doc in loaded_documents}
assert loaded_documents == documents and loaded_ids == index_doc_ids

verification_query = embed_question(QUESTION)
k = min(TOP_K, index.ntotal)
before_scores, before_positions = index.search(verification_query, k)
after_scores, after_positions = loaded_index.search(verification_query, k)
np.testing.assert_array_equal(before_positions, after_positions)
np.testing.assert_allclose(before_scores, after_scores, atol=1e-6, rtol=1e-6)

all_scores = (embeddings @ verification_query[0]).ravel()
expected_top_scores = np.sort(all_scores)[::-1][:k]
np.testing.assert_allclose(after_scores[0], expected_top_scores, atol=1e-5, rtol=1e-5)
np.testing.assert_allclose(after_scores[0], all_scores[after_positions[0]], atol=1e-5, rtol=1e-5)
print("通過：檔案完整性、文件對照、索引維度、保存前後一致，以及精確搜尋檢查。")

通過：檔案完整性、文件對照、索引維度、保存前後一致，以及精確搜尋檢查。

## 16. 打包並下載知識庫

ZIP 根目錄包含前述四個檔案。下載後，留給第二份 Colab 上傳使用；模型權重不在 ZIP 裡。

In [ ]:
EXPORT_ZIP = EXPORT_DIR.parent / f"{EXPORT_DIR.name}_download" / EXPORT_ZIP_NAME
EXPORT_ZIP.parent.mkdir(parents=True, exist_ok=True)
required_files = ["index.faiss", "documents.json", "index_doc_ids.json", "config.json"]
with zipfile.ZipFile(EXPORT_ZIP, "w", compression=zipfile.ZIP_DEFLATED) as archive:
    for name in required_files:
        archive.write(EXPORT_DIR / name, arcname=name)
with zipfile.ZipFile(EXPORT_ZIP) as archive:
    assert archive.testzip() is None
    assert set(archive.namelist()) == set(required_files)
print("下載檔名：", EXPORT_ZIP_NAME)
print("大小：", f"{EXPORT_ZIP.stat().st_size:,} bytes")
files.download(str(EXPORT_ZIP))

下載檔名： vector_db.zip
大小： 44,988 bytes